# Configuração do PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/people
quarkus.datasource.username=${USERDB}
quarkus.datasource.password=${PASSDB}