# Configuração do PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/people
quarkus.datasource.username=${USERDB}
quarkus.datasource.password=${PASSDB}

# Enables displaying SQL queries in the console
quarkus.hibernate-orm.log.sql=true

# Formats the generated SQL to be structured and readable across multiple lines
quarkus.hibernate-orm.log.format-sql=true

# (Optional) Displays the actual parameter values passed (replaces '?' with the values)
quarkus.hibernate-orm.log.bind-parameters=true

# Disable table creation
quarkus.hibernate-orm.database.generation=none

# Default level for development, test, or other environments (INFO)
quarkus.log.level=INFO

# Overrides to WARN strictly when the application runs in production mode (%prod)
%prod.quarkus.log.level=WARN